#!/usr/bin/env python3
"""Rebuild assets/kits/kits.json from the Google Drive event-kit folder.

Input  : assets/kits/drive-index.tsv   ("<fileId>\t<filename>", one per line;
                                        lines starting with # are ignored)
Output : assets/kits/kits.json
         sheet-seed/EventKits.csv      (hero_image column refreshed)

The images are NOT copied into the repo — they are hotlinked straight off
Drive, which is why the folder must stay shared "Anyone with the link -
Viewer". Downloading them is impractical from here: egress to Drive is blocked
from both shells, and the Drive connector only returns base64 through the
conversation (~33MB for the current set).

WHICH KIT AN IMAGE BELONGS TO IS DECIDED BY ITS FILENAME PREFIX (below).
The trailing number is ordering only, and the LOWEST-numbered file in a kit
becomes that kit's hero image. To add photography: rename the files to match a
prefix, drop them in the Drive folder, refresh drive-index.tsv from a folder
listing, and re-run this script.
"""
import csv, io, json, os, re
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, 'assets', 'kits', 'drive-index.tsv')
OUT = os.path.join(ROOT, 'assets', 'kits', 'kits.json')
SEED = os.path.join(ROOT, 'sheet-seed', 'EventKits.csv')

FOLDER_ID = '1ox803NP73FVxxPTScm0DbB41sZPetc4T'

# prefix -> event kit slug. Both the long and short spellings are accepted so
# whoever is naming files can use whichever is convenient.
RULES = [
    (r'^(New-Joinee-Kit|NJ)-',                    'new-joinee-program'),
    (r'^(Employee-Recognition-&-Rewards|ERR)-',   'employee-recognition-rewards'),
    (r'^(New-Mom-&-Baby-kit|wm)-',                'new-mom-baby-kit'),
    (r'^(Sustainable|SUS)-',                      'sustainability'),
    (r'^(Festive-Gift-Kits|FG)-',                 'festive-gift-kits'),
    (r'^(Personal-Milestone|PM)-',                'personal-milestone'),
    (r'^(CXO-Gifting|CXO)-',                      'cxo-gifting'),
    (r'^(Executive-Gifting|EXEC)-',               'executive-gifting'),
]

ORDER = ['new-joinee-program', 'employee-recognition-rewards', 'new-mom-baby-kit',
         'sustainability', 'festive-gift-kits', 'personal-milestone',
         'cxo-gifting', 'executive-gifting']


def sort_key(filename):
    """Order within a kit: by the trailing number, then the name."""
    m = re.search(r'-(\d+)\s*\.[A-Za-z0-9]+$', filename)
    return (int(m.group(1)) if m else 10**6, filename.lower())


def url(file_id, width):
    return f'https://lh3.googleusercontent.com/d/{file_id}=w{width}'


def main():
    buckets = defaultdict(list)
    unmapped = []

    with open(INDEX, encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if not line.strip() or line.lstrip().startswith('#'):
                continue
            file_id, _, name = line.partition('\t')
            if not name:
                continue
            for pattern, slug in RULES:
                if re.match(pattern, name, flags=re.I):
                    buckets[slug].append({'id': file_id.strip(), 'file': name.strip()})
                    break
            else:
                unmapped.append(name.strip())

    for slug in buckets:
        buckets[slug].sort(key=lambda x: sort_key(x['file']))

    out = {
        '_note': (f'Event-kit imagery. Source: Google Drive folder {FOLDER_ID} '
                  '(catalogue@companystore.io). The folder must stay shared '
                  '"Anyone with the link - Viewer" for these URLs to resolve for site '
                  'visitors. Generated by tools/build_kit_media.py from '
                  'assets/kits/drive-index.tsv — edit that, not this file.'),
        'kits': {},
    }
    for slug in ORDER:
        imgs = buckets.get(slug, [])
        out['kits'][slug] = {
            'hero': url(imgs[0]['id'], 1200) if imgs else '',
            'gallery': [{'src': url(i['id'], 1200), 'thumb': url(i['id'], 600), 'file': i['file']}
                        for i in imgs],
        }

    with open(OUT, 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
        f.write('\n')

    # keep the seed CSV's hero_image column in step, for future re-imports
    if os.path.exists(SEED):
        rows = list(csv.DictReader(open(SEED, encoding='utf-8')))
        for r in rows:
            r['hero_image'] = out['kits'].get(r['slug'], {}).get('hero', '')
        buf = io.StringIO()
        w = csv.DictWriter(buf, fieldnames=list(rows[0].keys()), lineterminator='\n')
        w.writeheader()
        w.writerows(rows)
        open(SEED, 'w', encoding='utf-8').write(buf.getvalue())

    total = sum(len(v) for v in buckets.values())
    print(f'{total} image(s) mapped\n')
    for slug in ORDER:
        n = len(buckets.get(slug, []))
        hero = buckets[slug][0]['file'] if n else '—'
        print(f'  {slug:32} {n:>3}   hero: {hero}')
    if unmapped:
        print('\nNOT MAPPED — filename matches no prefix rule:')
        for n in unmapped:
            print('  ' + n)
        print('\nAccepted prefixes (case-insensitive, N = ordering number):')
        for pattern, slug in RULES:
            forms = re.search(r'\((.+?)\)', pattern)
            names = forms.group(1).split('|') if forms else [pattern.strip('^-')]
            print(f'  {slug:32} ' + '  '.join(n + '-N' for n in names))


if __name__ == '__main__':
    main()
